# Generated by Django 4.2.7 on 2025-07-28 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0002_initial'),
        ('trades', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='recipient_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trade',
            name='recipient_offered_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipient_offered_trades', to='books.book'),
        ),
        migrations.AddField(
            model_name='trade',
            name='requester_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trade',
            name='trade_type',
            field=models.CharField(choices=[('swap', 'Book Swap'), ('donation', 'Donation')], default='swap', max_length=20),
        ),
        migrations.AlterField(
            model_name='trade',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='TradeMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_messages', to=settings.AUTH_USER_MODEL)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='trades.trade')),
            ],
            options={
                'db_table': 'trade_messages',
                'ordering': ['created_at'],
            },
        ),
    ]
