# Generated by Django 4.2.7 on 2025-07-29 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publication',
            field=models.CharField(blank=True, help_text='Publisher name (optional)', max_length=200),
        ),
    ]
