# Generated by Django 4.2.7 on 2025-07-29 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='successful_trades_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
